---
dontChroot: false
timeout: 30
exec:
    - "rm -f /etc/sddm.conf.d/autologin.conf"
    - "rm -f /usr/share/applications/calamares-install-debian.desktop"
    - "rm -f /etc/xdg/autostart/calamares-desktop-icon.desktop"
    - "sed -i '/^\\[Autologin\\]/,/^\\[/{/^\\[Autologin\\]/d; /^\\[/!d}' /etc/sddm.conf.d/kde_settings.conf"
    - "rm -rf /etc/lightdm/lightdm.conf.d/*"
    - "userdel -r -f live"
