[Autologin]
Relogin=false
Session=plasma.desktop
User=live

[General]
HaltCommand=
Numlock=on
RebootCommand=

[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1

[Users]
MaximumUid=60000
MinimumUid=1000
